### PR TITLE
Use telluric API to download data

### PR DESCRIPTION
**Pull request by astrojuanlu**
Already updated Gambia notebook, missing the rest.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
We still have to sort out some permission errors and the directories of the data, I'd say the rest is ready.

**Comment by brunosan** [comment]
I've added an option to download the rasters directly, which works, but is very slow since it's uncompressed and serial.

**Comment by astrojuanlu** [comment]
For performance, perhaps something like this would be better:

```
from requests_threads import AsyncSession

session = AsyncSession(n=100)

async def _main():
    rs = []
    for _ in range(100):
        rs.append(await session.get('http://httpbin.org/get'))
    print(rs)

if __name__ == '__main__':
    session.run(_main)
```

(from https://github.com/requests/requests-threads#examples)

Do you think it's worth it to add this kind of asynchronous code, or prefer to keep it simple for our users?

**Comment by astrojuanlu** [comment]
Also, the widget solution uses 100 % CPU in my computer, FYI.

**Review by brunosan — APPROVED** [review]
🎉

**Pull request merged**
