### PR TITLE
Fresh start hicups

### PR DESCRIPTION
**Pull request by brunosan**
Had to add this when doing a fresh install, on OSX 10.13.4, whith the new pip `telluric`.

@Juanlu001 is this expected, then merge? or an issue upstream on `telluric`.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
I tried to reproduce this using `pip install --no-cache-dir telluric` just to make sure that I was not using any pre-cached wheels and I didn't need cython. Before we merge this, can you try

```
$ conda remove -n satellogic --all
$ conda env create
$ source activate satellogic
$ pip install --no-cache-dir telluric -vv
```

And paste the output here?

**Comment by astrojuanlu** [comment]
By the way:

https://mail.python.org/pipermail/python-announce-list/2018-April/011885.html

**Comment by astrojuanlu** [comment]
(to fix the above, `conda update pip`)

**Comment by brunosan** [comment]
no luck
https://gist.github.com/brunosan/86b063888d7f6162dde8f1ed1e7697de

**Comment by astrojuanlu** [comment]
Sorry, didn't see you linked https://github.com/jswhit/pyproj/issues/103.

Can you try `conda install proj4` before `pip install pyproj` and paste the verbose output again?

**Comment by brunosan** [comment]
after `conda install proj4`
https://gist.github.com/brunosan/3104941040ce63e5a754184b99412e09
pip fails with `pip install --no-cache-dir pyproj -vv`
https://gist.github.com/brunosan/f14aceb38eba7b189add725c8b6b8a2e

with PR still works (both needs cython and pip from that user's github
https://gist.github.com/brunosan/b38903f819d1d0ff1e1d0485c169be0d

**Comment by astrojuanlu** [comment]
Well, definitely there's not much we can do. Perhaps we should specify that these are OS X - specific steps though?

**Review by astrojuanlu — APPROVED** [review]

**Pull request merged**
